=== cevers/EARS-Map-Objects/matlab/map.dtd
<!-- ******************* Definition of the environment trajectory used for EARS. ******************* 
	Author: Christine Evers, c.evers@imperial.ac.uk
	Changelog: 
		2014-06-18 - v1.0 Baseline
		2014-07-20 - v1.1 Updated structures to reflect that of Matlab map objects.
		2014-08-07 - v1.2 Updated map object fields and documentation.
-->

<!-- Note on defining DTDs:
	Inputs to elements can have the following properties:
	+ for specifying that there must be one or more occurrences of the item — the effective content of each occurrence may be different;
	* for specifying that any number (zero or more) of occurrences is allowed — the item is optional and the effective content of each occurrence may be different;
	? for specifying that there must not be more than one occurrence — the item is optional;
If there is no quantifier, the specified item must occur exactly one time at the specified state in the content of the element. 
-->

<!-- ***** DEFINE MAP *****
	 Allow map to contain multiple mapObjects by using * -->
<!ELEMENT map (mapObject*)>
	<!ATTLIST map version CDATA #REQUIRED>
	<!ATTLIST map date CDATA #REQUIRED>

	<!-- ***** DEFINE UPDATE *****
		Map objects are added to the XML file whenever an update (or prediction) becomes available. Each object is associated with a time stamp such that
		the XML file can be parsed and the time trajectory extracted.
		
		Each mapObject is assigned a 
	-->
	
	<!ELEMENT mapObject (type, ID, observationID, soundURL, isMoving, makesSound, reflectsSound, isVisible, position, covariance, initTime, updateTime)>
		<!ATTLIST mapObject objectID ID #REQUIRED>
		<!ELEMENT type (#PCDATA)>
		<!ELEMENT ID (#PCDATA)>
		<!ELEMENT observationID (#PCDATA)>
		<!ELEMENT soundURL (#PCDATA)>
		
		<!ELEMENT isMoving (#PCDATA)>
		<!ELEMENT makesSound (#PCDATA)>
		<!ELEMENT reflectsSound (#PCDATA)>
		<!ELEMENT isVisible (#PCDATA)>
		
		<!ELEMENT position (#PCDATA)>
		<!ELEMENT covariance (#PCDATA)>
				
		<!ELEMENT initTime (#PCDATA)>
		<!ELEMENT updateTime (#PCDATA)>

=== cevers/EARS-Map-Objects/matlab/example_map.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE map SYSTEM "map.dtd">
<!-- Validate this file against DTD definition using the command xmllint -valid -dtdvalid map.dtd -noout example_map.xml -->
<map version="1.0" date="2014-06-18 18:50:31">

	<!-- Define current knowledge about NAO 
		 Example defines Nao located at position [3 3 .8]m in the room. Uncertainties assumed as 0.2 m^2 in position .
	-->
	<mapObject objectID="NAO_0001">
		<ID>0</ID>
		<isMoving> 1 </isMoving>
		<makesSound> 1 </makesSound>
		<reflectsSound> 1 </reflectsSound>
		<isVisible> 0 </isVisible>
		<observationID> 1 </observationID>
		<position> [3; 3; .8] </position>
		<covariance> [0.2 0 0; 0 0.2 0; 0 0 0.2] </covariance>
		<time> 1 </time>
	</mapObject>
		
	<mapObject objectID="track_0001">
		<!-- Define first point source -->
		<ID> 1 </ID>
		<observationID> 8 </observationID>
		<isMoving> 1 </isMoving>
		<makesSound> 1 </makesSound>
		<reflectsSound> 0 </reflectsSound>
		<isVisible> 1 </isVisible>
		<position> [2.8; 2; 1.8]</position>
		<covariance> [0.2 0 0; 0 0.1 0; 0 0 0.1]</covariance>
		<time> 1 </time>
	</mapObject>
	
	<mapObject objectID="NAO_0002">
		<ID>0</ID>
		<observationID> 2 </observationID>
		<isMoving> 1 </isMoving>
		<makesSound> 1 </makesSound>
		<reflectsSound> 1 </reflectsSound>
		<isVisible> 0 </isVisible>
		<position> [3; 3; .8] </position>
		<covariance> [0.2 0 0; 0 0.2 0; 0 0 0.2] </covariance>
		<time> 2 </time>
	</mapObject>

	<mapObject objectID="track_0002">
		<ID> 1 </ID>
		<observationID> 10 </observationID>
		<isMoving> 1 </isMoving>
		<makesSound> 1 </makesSound>
		<reflectsSound> 0 </reflectsSound>
		<isVisible> 1 </isVisible>
		<position> [3; 2; 1.8] </position>
		<covariance> [0.2 0 0; 0 0.1 0; 0 0 0.1]</covariance>
		<time>2</time>
	</mapObject>
</map>
